# -*- coding: utf-8 -*-
"""utils.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VBCvApmJnsS0OnHsh1HzzCAshK36j5p_
"""

from requests import Session
import re

def build_header(headerstring):
  '''
  Make header dictionary automatically.
  header string format sould be :
    key: value
    key: value
  returns header(dict)
  '''
  header = dict()
  for line in headerstring.splitlines():
    if len(line) > 0 and line[0] != ':':
      kv = re.search('^(.+)?: (.*)', line)
      try:
        header[kv.group(1)] = kv.group(2)
      except:
        pass
  return header

def set_cookies(session, c):
  '''
  set cookies for session
  '''
  for _ in c.splitlines():
    if len(_) > 1:
      kv = _.split('\t')
      session.cookies.set(kv[0],kv[1])
  return session